name: CI

on:
  push:
    branches:    
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1

    - uses: ammaraskar/sphinx-action@0.4
      with:
        pre-build-command: "pip install sphinx_rtd_theme"
        docs-folder: "."

    - uses: actions/upload-artifact@v1
      with:
        name: DocumentationHTML
        path: ./_build/html/
        
    - name: Add .nojekyll file
      run: sudo touch ./_build/html/.nojekyll
                
    - name: GitHub Pages
      uses: crazy-max/ghaction-github-pages@v1.4.1
      with:
        build_dir: ./_build/html
      env:
        GITHUB_PAT: ${{ secrets.PAT }}
